config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/todos', to: 'todos#index'
  post '/todos/:id/finish', to: 'todos#finish'
  post '/todos/:id/activate', to: 'todos#activate'
  put '/todos', to: 'todos#create'
  delete '/todos/:id', to: 'todos#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :text, presence: true
    after_initialize :init

    belongs_to :user

    def init
        self.done ||= false
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :tasks

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    unless session[:user_id].nil?
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def require_login
    if current_user.nil?
      flash[:error] = "You must be logged in!"
      redirect_to login_path
      puts "Not logged in!"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:user][:email])

    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to todos_path, notice: "Logged in!"
    else
      flash.now[:alert] = "Email/password combination not found!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: "Logged out!"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :require_login

  def index
    @tasks = current_user.tasks

    respond_to do |format| 
      format.html
      format.json { render json: @tasks }
    end
  end

  def create
    @task = Task.new(params.require(:todo).permit(:text))
    @task.user = current_user

    if @task.save then
      render json: @task
    else
      render json: @task, status: 400
    end
  end

  def finish
    @task = current_user.tasks.find(params[:id])
    @task.done = true
    @task.save

    render json: @task
  end

  def activate
    @task = current_user.tasks.find(params[:id])
    @task.done = false
    @task.save

    render json: @task
  end

  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy

    render json: { success: true }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to todos_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        puts @user.errors.any?
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<%= javascript_pack_tag 'hello_svelte' %>

app/views/users/new.html.erb
<div class="card form">
    <h1>Register</h1>
    <hr>

    <%= form_for @user, url: register_path do %>
        <%= email_field :user, :email, placeholder: "Email" %>
        <%= password_field :user, :password, placeholder: "Password" %>
        <%= password_field :user, :password_confirmation, placeholder: "Confirm password" %>
        <%= submit_tag "Register", class: "greenbtn" %>
    <% end %>
</div>